"""Pipeline alt-beceri dosyalarını tek veri kaynağından üretir.

Her alt-beceri = pipeline/<aşama>/steps/NN-<ad>.md
Format: amaç, komut, girdi->çıktı, prosedür, kapıya katkı.
"""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent / "pipeline"

# (aşama_dizini, [(no, ad, komut, amaç, girdi, çıktı, prosedür_satırları, kapı_katkısı)])
PIPELINE: list[tuple[str, list[tuple]]] = [
    ("00-needs", [
        ("01", "Fikir Yakalama", "/dump",
         "Ham fikri hiç yargılamadan kayda almak. Dağınıklık serbest.",
         "Kafandaki her şey (sesli düşünme, yarım cümleler)",
         "RAW-XXX.md — işlenmemiş döküm",
         ["Kullanıcının yazdığını AYNEN kaydet, düzeltme.",
          "Sadece anlaşılmayan kelimeleri işaretle [?].",
          "Yorum yok, çözüm yok, soru yok — bu adımda sessiz kal."],
         "Ham malzeme kaybolmaz; sonraki adımlar buna döner."),
        ("02", "Sorgu Yağmuru", "/grill-need",
         "Belirsiz hiçbir şey kalmayana kadar soru sormak.",
         "RAW-XXX.md",
         "Cevaplanmış soru listesi (NEED'in hammaddesi)",
         ["Kim kullanacak? Ne sıklıkla? Neyin yerine geçiyor?",
          "Yanlış olursa ne kaybedilir (para/zaman/güvenlik)?",
          "Soruları TOPLU sor (tek mesaj), cevapları kaydet.",
          "Cevapsız soru = NEED'e 'Açık Soru' olarak taşınır."],
         "Problem tek cümlede yazılabilir hale gelir."),
        ("03", "Kapsam Bıçağı", "/scope",
         "Neyin İÇERİDE neyin DIŞARIDA olduğunu keskinleştirmek.",
         "Sorgu cevapları",
         "Kapsam içi / kapsam dışı / v-sonraki listeleri",
         ["Her özellik adayını 3 kovaya at: ŞİMDİ / SONRA / ASLA.",
          "SONRA ve ASLA gerekçeli — 'belki' kovası YOK.",
          "ŞİMDİ kovası 1 görevde bitecek kadar küçük mü? Değilse böl."],
         "Kapsam DIŞI >= 1 madde gate şartı sağlanır."),
        ("04", "Ölçüt Mühendisi", "/measure",
         "Başarıyı sayıya bağlamak. Ölçemediğin şeyi teslim edemezsin.",
         "Kapsam listesi",
         "Sayısal başarı ölçütleri (tolerans + kaynak)",
         ["Her ölçüt: <metrik> <karşılaştırma> <değer> <koşul>.",
          "Ör: 'Iy, katalog değeriyle ±%3 içinde (fillet farkı gerekçeli)'.",
          "Ölçülemeyen istek varsa 02'ye dön, soruyu netleştir."],
         "Gate: 'başarı ölçütü sayısal/doğrulanabilir' işaretlenir."),
        ("05", "Önceliklendirme", "/prioritize",
         "P0/P1/P2 atamak ve NEED-XXX.md'yi finalize etmek.",
         "Önceki tüm adım çıktıları",
         "Tamamlanmış NEED-XXX.md (şablona dökülmüş)",
         ["P0=iş duruyor, P1=verim kaybı, P2=iyileştirme.",
          "TEMPLATE.md'yi doldur, gate checklist'ini işaretle.",
          "Kullanıcı onayını al -> 01-prompts'a geç."],
         "Tüm gate maddeleri kapanır; aşama biter."),
    ]),
    ("01-prompts", [
        ("01", "Prompt Maker", "/prompt-maker",
         "Onaylı NEED'i ilk taslak yönergeye dönüştürmek: dağınık->yapılı.",
         "NEED-XXX.md",
         "PROMPT-XXX.draft.md (rol/bağlam/görev/format/kısıt iskeleti)",
         ["NEED'deki problemi GÖREV cümlesine çevir (tek eylem).",
          "Rol ata: hangi uzmanlık şapkası? (ör. EN 1993 + Python)",
          "Bağlam bölümüne: ilgili src/ modülleri, DECISIONS kayıtları."],
         "Yapılı taslak var; sonraki adımlar bunu rafine eder."),
        ("02", "Grill Me", "/grill-me",
         "Taslaktaki her belirsiz terimi sorguya çekmek.",
         "PROMPT-XXX.draft.md",
         "Belirsizlik listesi + çözümleri",
         ["Her ismi/fiili tara: birimi var mı, tanımı tek mi?",
          "'Hızlı', 'uygun', 'standart' gibi kelimeler YASAK — sayıya çevir.",
          "Cevabı NEED'de olmayan soru -> kullanıcıya toplu sor."],
         "Gate: 'belirsiz terim kalmadı' işaretlenebilir."),
        ("03", "How To", "/how-to",
         "Görevin gerektirdiği ama henüz bilinmeyen adımları haritalamak.",
         "Netleşmiş taslak",
         "Bilgi boşluğu haritası + okunacak kaynak listesi",
         ["Görevi kabaca adımlara böl; her adım için 'nasıl yapılır biliniyor mu?'",
          "Bilinmeyenler için: skills/ dosyası mı, standart mı, researcher subagent mı?",
          "Okunacaklar listesini PROMPT'un Bağlam bölümüne yaz."],
         "Gate: 'okunacak skills listelendi' sağlanır."),
        ("04", "Optimizer", "/optimize-prompt",
         "Yönergeyi model için sıkılaştırmak: sıra, vurgu, format.",
         "Taslak + bilgi haritası",
         "Optimize edilmiş yönerge gövdesi",
         ["Kritik kısıtları başa ve sona koy (primacy/recency).",
          "Uzun paragrafları maddelere kır; her madde tek talimat.",
          "Çıktı formatını ŞEMA olarak ver (dosya adı, imza, birim)."],
         "Yönerge modelin yanlış yorumlayamayacağı forma gelir."),
        ("05", "Alan Sesi", "/domain-voice",
         "Yönergeyi projenin mühendislik diline oturtmak.",
         "Optimize gövde",
         "Terminolojisi projeyle hizalı yönerge",
         ["EN gösterimi (Iy, Wel_y), SI-mm, TR açıklama dili uygula.",
          "skills/*/SKILL.md ile çelişen ifade var mı tara; varsa düzelt.",
          "Proje sözlüğünde olmayan yeni terim -> sözlüğe ekle."],
         "Yönerge, skill kurallarıyla %100 tutarlı."),
        ("06", "Anti-Halüsinasyon", "/anti-hallucination",
         "Modeli uydurmaya itebilecek her açığı kapatmak.",
         "Hizalı yönerge",
         "Güvenlik kilitleri eklenmiş yönerge",
         ["'Bilmiyorsan uydurma, sor' talimatını açıkça ekle.",
          "Referans değeri olmayan sayısal iddia YASAK kuralı ekle.",
          "Negatif örnek ekle: 'Şunu yaparsan yanlış: <örnek>'."],
         "Gate: 'en az 1 pozitif + 1 negatif örnek' sağlanır."),
        ("07", "Beceri Damıtma", "/write-a-skill",
         "Bu görevde öğrenilen genellenebilir kuralı skills/'e bottlelamak.",
         "Final yönerge + görüşme notları",
         "skills/ altında yeni/güncellenmiş SKILL.md bölümü",
         ["Sor: bu kural GELECEK görevlerde de geçerli mi?",
          "Evetse ilgili SKILL.md'ye kısa kural olarak ekle (tarih + görev no).",
          "Hayırsa sadece PROMPT'ta kalır — skill şişirilmez."],
         "Kurumsal hafıza büyür; tekrar iş azalır."),
        ("08", "Devir Paketi", "/handoff",
         "PROMPT-XXX.md'yi finalize edip 02-spec'e devretmek.",
         "Tüm adım çıktıları",
         "PROMPT-XXX.md (final) + devir notu",
         ["TEMPLATE.md formatına dök, gate checklist işaretle.",
          "Spec yazacak oturumun ihtiyacı olan HER ŞEY içinde mi? Testi: ",
          "bu dosya tek başına yeni bir sohbete verilse spec yazılabilir mi?"],
         "Aşama biter; bağlam kaybı olmadan 02'ye geçilir."),
    ]),
    ("02-spec", [
        ("01", "Gereksinim Çıkarımı", "/fr-extract",
         "PROMPT'tan numaralı, test edilebilir FR'ler türetmek.",
         "PROMPT-XXX.md",
         "FR-1..N tablosu (taslak)",
         ["Her FR tek cümle, tek doğrulanabilir davranış.",
          "'ve' içeren FR'yi ikiye böl.",
          "FR'ler NEED başarı ölçütlerini TAM kapsıyor mu çapraz kontrol."],
         "FR listesi izlenebilirliğin temelini atar."),
        ("02", "Arayüz Sözleşmesi", "/interface",
         "İmzaları, birimleri ve hata davranışını sabitlemek.",
         "FR tablosu",
         "Python imzaları + docstring sözleşmeleri",
         ["Her public fonksiyon: imza + param birimleri + dönüş tipi.",
          "Her hata koşulu: hangi exception, hangi mesajla.",
          "Sözleşme sonradan değişirse -> spec revizyonu + onay tazeleme."],
         "Gate: 'arayüz sözleşmesi tam' işaretlenir."),
        ("03", "Kabul Testi Tanımı", "/acceptance",
         "Her FR'ye referans değerli kabul testi bağlamak.",
         "FR + arayüz",
         "FR başına: referans değer, tolerans, KAYNAK",
         ["Kaynak hiyerarşisi: el hesabı > standart tablosu > katalog.",
          "Analitik formül: rel_tol=1e-9. Katalog karşılaştırma: tolerans gerekçeli.",
          "Kaynağı olmayan FR -> 01-prompts/03-how-to'ya geri dön."],
         "Gate: 'her FR için kabul testi' sağlanır."),
        ("04", "Fonksiyonel Olmayanlar", "/nonfunctional",
         "Performans, tip, coverage, güvenlik eşiklerini yazmak.",
         "FR seti",
         "NFR bölümü (ölçülebilir eşikler)",
         ["Varsayılan: mypy strict, coverage>=90, ruff temiz.",
          "Göreve özel: süre limiti, bellek, dosya boyutu vb. varsa ekle.",
          "Her NFR'nin CI'da NASIL ölçüleceğini belirt."],
         "Kalite kapıları spec'te sözleşmeye bağlanır."),
        ("05", "Açık Soru Avı", "/open-questions",
         "Onay öncesi tüm kararsızlıkları yüzeye çıkarmak.",
         "Spec taslağının tamamı",
         "Açık soru listesi (sahipli, son tarihli)",
         ["Taslağı satır satır oku: 'burada iki türlü anlaşılır mı?'",
          "Her açık soru: kim cevaplayacak + hangi adımda bloklar.",
          "Sıfır açık soru şüphelidir — en az bir tur zorunlu."],
         "Onaya temiz spec gider; build sürprizi azalır."),
        ("06", "Onay Kapısı", "/approve-spec",
         "Kullanıcı onayını almak ve durumu ONAYLI'ya çekmek.",
         "Açık soruları kapanmış spec",
         "SPEC-XXX.md Durum: ONAYLI + onay kaydı",
         ["Spec'i kullanıcıya ÖZET + tam metin olarak sun.",
          "Onay açık ifade olmalı; sessizlik onay DEĞİLDİR.",
          "Onay tarihi ve kapsamı spec'e işlenir. Değişiklik = re-onay."],
         "Gate: 'kullanıcı onayı alındı' — build kilidi açılır."),
    ]),
    ("03-plan", [
        ("01", "İş Kırılımı", "/wbs",
         "Spec'i <= yarım günlük iş paketlerine bölmek.",
         "ONAYLI SPEC",
         "WP tablosu (çıktı + doğrulama tanımlı)",
         ["Her WP'nin çıktısı somut dosya/fonksiyon olmalı.",
          "Her WP'nin doğrulaması: hangi test/komut yeşil olacak?",
          "Yarım günden büyük WP -> böl."],
         "Gate: 'her paket <= yarım gün' sağlanır."),
        ("02", "Risk Matrisi", "/risk",
         "Ne ters gidebilir + B planı üretmek.",
         "WP tablosu",
         "Risk tablosu (olasılık x etki + B planı)",
         ["Her WP için: teknik risk? bilgi eksiği? bağımlılık riski?",
          "Yüksek risk x yüksek etki -> WP sırasında öne al.",
          "B planı 'daha çok çalışırız' olamaz — somut alternatif."],
         "Gate: 'geri dönüş planı' sağlanır."),
        ("03", "Sıralama", "/sequence",
         "Bağımlılık grafiği + fail-fast sıra.",
         "WP + risk",
         "Sıralı yürütme listesi",
         ["Bağımlılıkları çiz: WP-x, WP-y'yi bekliyor mu?",
          "EN RİSKLİ bağımsız paket İLK — erken batacaksa ucuz batsın.",
          "Paralelleştirilebilir paketleri işaretle (subagent adayı)."],
         "Gate: 'en riskli paket ilk' sağlanır."),
        ("04", "Mimari Karar Kaydı", "/adr",
         "Geri dönüşü pahalı kararları ADR'ye bağlamak.",
         "Plan taslağı",
         "docs/adr/ADR-N.md (gerekiyorsa)",
         ["Test: bu karar 3 ay sonra 'neden böyle?' sorusu doğurur mu?",
          "Evetse ADR: bağlam, seçenekler, karar, sonuçlar.",
          "Hayırsa DECISIONS.md satırı yeter."],
         "Kararların gerekçesi kaybolmaz."),
        ("05", "Plan Yayını", "/publish-plan",
         "PLAN-XXX.md'yi finalize edip build'i tetiklemek.",
         "Tüm plan bileşenleri",
         "PLAN-XXX.md final",
         ["TEMPLATE'e dök, gate checklist'i işaretle.",
          "Riskli işte (P0 / geri dönüşsüz) kullanıcıya planı göster.",
          "feat/task-XXX branch adını ilan et -> 04-build."],
         "Aşama biter; build net talimatla başlar."),
    ]),
    ("04-build", [
        ("01", "Dal Açılışı", "/branch",
         "Temiz başlangıç: branch + iskelet dizinler.",
         "PLAN-XXX.md",
         "feat/task-XXX branch + boş modül iskeleti",
         ["main güncel mi? pull. Sonra branch aç.",
          "Modül/test dosyalarını BOŞ iskelet olarak oluştur, commit et.",
          "Bu commit 'sıfır noktası' — sonraki diff'ler temiz okunur."],
         "İzlenebilir, geri alınabilir başlangıç."),
        ("02", "TDD Çekirdeği", "/tdd-core",
         "Önce kabul testini yaz (kırmızı), sonra kodu (yeşil).",
         "SPEC kabul testleri",
         "Test-önce implementasyon döngüsü",
         ["SPEC'teki referans değerli testi AYNEN koda dök -> kırmızı.",
          "Minimum kodu yaz -> yeşil. Refactor -> hâlâ yeşil.",
          "Referanssız kod yazma dürtüsü = spec'e dön sinyali."],
         "Kod, spec'ten sapamaz — test tasması takılı."),
        ("03", "Paket Yürütme", "/execute-wp",
         "WP'leri sırayla kapatmak, her biri commit'le.",
         "Sıralı WP listesi",
         "WP başına >= 1 commit + log satırı",
         ["WP başla -> kodla -> WP doğrulaması yeşil -> commit.",
          "Commit mesajı: 'WP-N: <özet>' + gövdede karar notu.",
          "3 denemede geçmeyen doğrulama -> DUR, sorunu raporla."],
         "Gate: 'tüm WP'ler commit'e bağlı' sağlanır."),
        ("04", "Sapma Dedektörü", "/drift-check",
         "Spec dışına kaymayı erken yakalamak.",
         "Güncel diff + SPEC",
         "Sapma raporu (temiz / sapma var)",
         ["Her 2-3 WP'de bir: diff'teki her public öğe spec'te var mı?",
          "Spec'te olmayan özellik -> ya sil ya spec revizyonu (onaylı).",
          "'Madem elim değmişken' kodu = sapma. İstisna yok."],
         "Gate: 'spec'ten sapma yok/işlendi' sağlanır."),
        ("05", "Build Kapanışı", "/close-build",
         "BUILD log'u tamamlayıp test aşamasına devretmek.",
         "Tüm WP'ler kapalı",
         "BUILD-XXX.log.md final",
         ["Log tablosunu doldur: süreler, sorunlar, çözümler.",
          "hooks'un son lint+test çıktısını yapıştır.",
          "Yarım kalan/ertelenen iş varsa AÇIKÇA listele -> 05-test'e."],
         "Aşama şeffaf biter; test aşaması sürprizsiz başlar."),
    ]),
    ("05-test", [
        ("01", "Referans Doğrulama", "/ref-test",
         "Her FR'yi kaynaklı referans değerle test etmek.",
         "SPEC kabul testleri + kod",
         "Referans test seti (kaynak docstring'de)",
         ["Kaynak (el hesabı/standart/katalog) test docstring'ine yazılır.",
          "Analitik: rel_tol=1e-9. Katalog: tolerans + gerekçe.",
          "Referansı doğrulanamayan FR -> K sınıfı bulgu olarak işaretle."],
         "Sayısal doğruluk kanıta bağlanır."),
        ("02", "Kenar Avcısı", "/edge-hunt",
         "Sıfır, negatif, sınır, taşma senaryolarını taramak.",
         "Arayüz sözleşmesi",
         "Parametrize kenar durum testleri",
         ["Her sayısal param için: 0, negatif, çok küçük, çok büyük.",
          "Geometrik tutarsızlıklar: hw<=0, t>b/2 gibi alan kuralları.",
          "Her kenar ya doğru sonuç ya TANIMLI hata vermeli — sessiz yanlış YASAK."],
         "Gate: kenar durumlar kapsandı."),
        ("03", "Hata Sözleşmesi", "/error-contract",
         "Doğru exception + doğru mesaj garantisi.",
         "Spec hata tanımları",
         "pytest.raises testleri (mesaj eşleşmeli)",
         ["Her hata koşulu: beklenen exception tipi VE mesaj içeriği.",
          "Genel Exception yakalama testte de kodda da yasak.",
          "Hata mesajı kullanıcıya girdisini geri söylemeli (debug kolaylığı)."],
         "Hatalar da davranıştır — sözleşmeye bağlanır."),
        ("04", "Fizik Invariantları", "/invariants",
         "Alan bilgisinden gelen değişmezleri test etmek.",
         "skills/ kuralları",
         "Invariant testleri",
         ["Ör: Wpl > Wel, A > 0, Iy simetride Iz'ye eşit vb.",
          "Rastgele geçerli girdilerle (hypothesis tarzı) tara.",
          "İhlal = formül hatası sinyali, tolerans artırarak geçiştirme."],
         "Formül düzeyi hatalar yakalanır."),
        ("05", "Kapsam ve Tip", "/coverage-type",
         "coverage>=90 + mypy strict + ruff kapılarını koşmak.",
         "Tam test seti",
         "Sayısal kapı çıktıları",
         ["pytest --cov, mypy --strict, ruff check koş, çıktıyı kaydet.",
          "Kapsanmayan satırları incele: ölü kod mu, test eksiği mi?",
          "Kapı altında kalan değer = aşama bitmez."],
         "Gate: coverage/mypy şartı sağlanır."),
        ("06", "İzlenebilirlik Matrisi", "/trace",
         "FR <-> test eşlemesini kanıtlamak + tester subagent koşusu.",
         "Tüm testler",
         "TEST-XXX.md (FR-test tablosu + subagent raporu)",
         ["Tabloyu doldur: her FR >= 1 test, her test >= 1 FR.",
          "Eşleşmeyen test = kapsam dışı iş sinyali -> drift-check'e bildir.",
          "tester subagent'ı BAĞIMSIZ koştur, raporunu ekle."],
         "Gate: izlenebilirlik tablosu tam."),
    ]),
    ("06-revise", [
        ("01", "Öz-İnceleme", "/self-review",
         "Reviewer'dan önce yazarın kendi temizliği.",
         "Tam diff",
         "Öz-inceleme notu",
         ["Diff'i BAŞTAN oku: yorumlar güncel mi, debug kalıntısı var mı?",
          "En utandığın 3 satırı bul ve düzelt (her diffte vardır).",
          "Reviewer'ın zamanını çöple harcama — ucuz hataları önce sen ayıkla."],
         "Review sinyal/gürültü oranı yükselir."),
        ("02", "Bağımsız İnceleme", "/agent-review",
         "reviewer subagent'ı taze bağlamla koşturmak.",
         "Temizlenmiş diff",
         "Ham bulgu listesi",
         ["Subagent'a SADECE diff + spec ver — build sohbet geçmişini VERME.",
          "Talimat: güvenlik -> birim/mantık -> kenar -> performans sırası.",
          "Bulgular dosya:satır formatında toplanır."],
         "Yazar körlüğü kırılır."),
        ("03", "Bulgu Triyajı", "/classify",
         "Bulguları K/M/m sınıflandırmak.",
         "Ham bulgular",
         "Sınıflı bulgu tablosu (REVIEW-XXX.md)",
         ["K: yanlış sonuç/güvenlik -> merge engeli.",
          "M: kenar/birim riski -> bu turda zorunlu.",
          "m: stil -> düzelt YA DA gerekçeli reddet. Sessiz yok sayma yasak."],
         "Her bulgunun akıbeti kayıtlı."),
        ("04", "Düzeltme Turu", "/fix-round",
         "K ve M'leri commit referanslı kapatmak.",
         "Sınıflı tablo",
         "Düzeltme commit'leri + güncel tablo",
         ["Her düzeltme ayrı commit: 'fix(REV-N): <özet>'.",
          "Düzeltme sonrası İLGİLİ testler + tam set tekrar yeşil.",
          "Düzeltme yeni bulgu doğurdu mu? Evetse tabloya ekle, döngü."],
         "Gate: 'K ve M kapandı' sağlanır."),
        ("05", "Ders Çıkarımı", "/lessons",
         "Tekrarlanabilir hataları kurumsal hafızaya işlemek.",
         "Kapanmış tablo",
         "DECISIONS.md [HATA] kayıtları + skill güncellemesi",
         ["Sor: bu bulgu sınıfı GELECEKTE nasıl otomatik yakalanır?",
          "Cevap lint kuralıysa -> pyproject'e; alan kuralıysa -> SKILL.md'ye.",
          "Kayıt formatı: [HATA] <kalıp> -> <önlem> (görev no)."],
         "Aynı hata ikinci kez ucuz yakalanır."),
    ]),
    ("07-simplify", [
        ("01", "Ölü Kod Taraması", "/deadcode",
         "Erişilmeyen/kullanılmayan her şeyi silmek.",
         "Review'dan çıkmış kod",
         "Silme commit'leri",
         ["vulture/coverage raporundan erişilmeyen dalları bul.",
          "Kullanılmayan import, değişken, parametre -> sil.",
          "'Belki lazım olur' -> SİL. Git hatırlar, sen hatırlama."],
         "Bakım yüzeyi küçülür."),
        ("02", "Tekrar Avı", "/dedupe",
         "Kopyala-yapıştır mantığı tekilleştirmek.",
         "Kod tabanı",
         "Ortak yardımcılara çekilmiş mantık",
         ["3+ satırlık benzer bloklar -> tek fonksiyon adayı.",
          "AMA: 2 kullanım için soyutlama ACELE olabilir — 3. kullanımı bekle.",
          "Soyutlama birimleri karıştırıyorsa yapma (mm+derece tek fonksiyonda olmaz)."],
         "DRY, dogma değil muhakeme ile uygulanır."),
        ("03", "API Küçültme", "/api-shrink",
         "Public yüzeyi savunulabilir minimuma indirmek.",
         "Modül exports",
         "Gerekçeli public API listesi",
         ["__all__ dışındaki her public öğe: dışarıdan çağrılıyor mu?",
          "Hayırsa _private yap. Belgesiz public öğe kalmasın.",
          "Her public öğe SIMPLIFY raporunda tek satır gerekçe alır."],
         "Gate: 'public API listelendi ve gerekçeli'."),
        ("04", "Doküman Senkronu", "/doc-sync",
         "Kod ile dokümanın aynı gerçeği anlatmasını sağlamak.",
         "Sadeleşmiş kod",
         "Güncel docstring/README/CHANGELOG taslağı",
         ["Her değişen imzanın docstring'i güncel mi?",
          "README örnekleri hâlâ ÇALIŞIYOR mu? (kopyala-koştur testi)",
          "Silinen özellik dokümandan da silinir — hayalet doküman yasak."],
         "Doküman güvenilir kalır."),
        ("05", "Davranış Kanıtı", "/prove-behavior",
         "Sadeleştirmenin hiçbir davranışı değiştirmediğini kanıtlamak.",
         "Tüm refactor commit'leri",
         "SIMPLIFY-XXX.md (önce/sonra + yeşil kanıt)",
         ["Testlere DOKUNULMADI mı? git diff tests/ boş olmalı.",
          "Tam set yeşil + coverage düşmedi kanıtını yapıştır.",
          "Önce/sonra satır sayısı; artmışsa gerekçe zorunlu."],
         "Gate: 'testler değişmeden yeşil' sağlanır."),
    ]),
    ("08-ship", [
        ("01", "Sürüm Kararı", "/version",
         "SemVer'e göre doğru sürüm numarasını seçmek.",
         "Diff + CHANGELOG",
         "vX.Y.Z kararı + pyproject güncellemesi",
         ["Kırıcı değişiklik var mı? (imza/davranış) -> MAJOR.",
          "Yeni özellik -> MINOR. Sadece düzeltme -> PATCH.",
          "Emin değilsen kırıcıdır — MAJOR seç, gerekçele."],
         "Sürüm anlamı korunur."),
        ("02", "Changelog Yazımı", "/changelog",
         "Değişiklikleri kullanıcı diliyle kaydetmek.",
         "Commit geçmişi",
         "CHANGELOG.md girdisi",
         ["Keep-a-Changelog: Eklendi/Değişti/Düzeltildi/Kaldırıldı.",
          "Commit mesajı kopyalama — KULLANICI etkisini yaz.",
          "Kırıcı değişiklikler EN ÜSTTE, geçiş talimatıyla."],
         "Sürüm geçmişi okunabilir kalır."),
        ("03", "Yayın Prosedürü", "/release",
         "PR merge + tag + GitHub release zinciri.",
         "CI yeşil branch",
         "Merge + vX.Y.Z tag + release notları",
         ["PR aç (squash), CI TÜM kapılardan geçmeli.",
          "Merge sonrası: git tag vX.Y.Z, gh release create --generate-notes.",
          "Release'e SHIP raporu linki eklenir."],
         "Gate: 'CI main'de yeşil' sağlanır."),
        ("04", "Kanıt Dosyası", "/evidence",
         "NEED'deki başarı ölçütünü ÖLÇÜP kapatmak.",
         "NEED-XXX ölçütleri + yayın",
         "SHIP-XXX.md kanıt bölümü",
         ["NEED'e dön, her ölçütü tek tek ÖLÇ (tahmin değil).",
          "Ölçüm çıktısını rapora yapıştır (test çıktısı, süre, karşılaştırma).",
          "Sağlanmayan ölçüt varsa ship DURUR — geriye hangi aşama, belirle."],
         "Gate: 'başarı ölçütü kanıtı' sağlanır."),
        ("05", "Retrospektif", "/retro",
         "Süreci puanlayıp pipeline'ın kendisini iyileştirmek.",
         "Tüm görev artefaktları",
         "Retro notu + pipeline iyileştirme önerisi",
         ["Hangi aşama en çok zaman yedi? Gate'lerden hangisi iş yaramadı?",
          "1 somut pipeline iyileştirmesi öner (şablon/komut/gate değişikliği).",
          "DECISIONS'a işle; kullanıcıya tek paragraf teslim özeti ver."],
         "Pipeline yaşayan sistem olur — kendi kendini iyileştirir."),
    ]),
]


def render(stage: str, s: tuple) -> str:
    no, name, cmd, purpose, inp, out, proc, gate = s
    proc_txt = "\n".join(f"{i+1}. {p}" for i, p in enumerate(proc))
    return f"""# {no} — {name}  `{cmd}`

**Amaç:** {purpose}

| | |
|---|---|
| **Girdi** | {inp} |
| **Çıktı** | {out} |

## Prosedür
{proc_txt}

## Kapıya Katkısı
{gate}
"""


def main() -> None:
    total = 0
    for stage, steps in PIPELINE:
        d = ROOT / stage / "steps"
        d.mkdir(parents=True, exist_ok=True)
        index = [f"# {stage} alt-beceri zinciri\n"]
        for s in steps:
            no, name, cmd = s[0], s[1], s[2]
            fname = f"{no}-{cmd.strip('/')}.md"
            (d / fname).write_text(render(stage, s), encoding="utf-8")
            index.append(f"{no}. **{name}** `{cmd}` — {s[3]}")
            total += 1
        (d / "INDEX.md").write_text("\n".join(index) + "\n", encoding="utf-8")
    print(f"{total} alt-beceri + 9 INDEX üretildi")


if __name__ == "__main__":
    main()
